### PR TITLE
do not copy methods. thunkify => yieldly

### PR DESCRIPTION
**Pull request by matthewmueller**
This PR does 2 things:
1. replace thunkify with yieldly (https://github.com/matthewmueller/yieldly)

Yieldly conditionally thunkifies functions depending on if a function was passed as the last argument or not. This allows us to support both generators and functions.
1. No longer copying methods and returning a new result

This breaks modules that add additional methods to leveldb, like `sublevel`.

### CODE REVIEW

**Comment by juliangruber** [comment]
:-1:, modules that require the untouched levelup instance might not always pass callbacks and we'd expect them to still work. I usually do something like this:

``` js
// lib/db.js
var db = level(__dirname + '/../db');
exports = wrap(db);
exports.orig = db;

// lib/some-module.js
var db = require('./db');
someModule(db.orig);
```

**Comment by matthewmueller** [comment]
ah interesting, do you know if its possible to have 2 instances of leveldb writing to the same DB location? becuase that would probably be cleaner.

**Comment by juliangruber** [comment]
you can have 2 instances of levelup using the same backend (like leveldown) but no, there can only be once instance of leveldb itself.

how would that be cleaner?

**Comment by matthewmueller** [comment]
> how would that be cleaner?

If I'm understanding it correctly, you could have two instances of levelup, writing to the same location. One that's wrapped in co-level, one that's unwrapped. So in your `lib` you could have... `lib/co-db` and `lib/db`, representing the wrapped and original levelup instances.

**Comment by juliangruber** [comment]
yeah that's what i meant :)

**Pull request closed without merging**
